### ISSUE TITLE
`yajl` missing

### ISSUE THREAD

**Issue by matthiasbeyer** [cstrahan/go2nix-OLD#5]
I simply did the following:

``` bash
$ nix-shell
# Waiting until things are installed
$ ./bin/go2nix --help
/nix/store/n5rp0d6njynn7n7mnvi40fvip4203chv-ruby-1.9.3-p547/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- yajl (LoadError)
        from /nix/store/n5rp0d6njynn7n7mnvi40fvip4203chv-ruby-1.9.3-p547/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/m/go2nix/lib/go2nix/go.rb:1:in `<top (required)>'
        from /nix/store/n5rp0d6njynn7n7mnvi40fvip4203chv-ruby-1.9.3-p547/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /nix/store/n5rp0d6njynn7n7mnvi40fvip4203chv-ruby-1.9.3-p547/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/m/go2nix/lib/go2nix.rb:1:in `<top (required)>'
        from /nix/store/n5rp0d6njynn7n7mnvi40fvip4203chv-ruby-1.9.3-p547/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /nix/store/n5rp0d6njynn7n7mnvi40fvip4203chv-ruby-1.9.3-p547/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from ./bin/go2nix:6:in `<main>'
```

**Comment by cstrahan** [comment]
Now that I have the better Ruby support in Nix, I intend to package this up properly.

**Comment by davidak** [comment]
still same issue:

```
go2nix --help
/nix/store/53q97ls0hz8nz12fia389ygkqq9nzxn2-ruby-2.3.1-p0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- yajl (LoadError)
    from /nix/store/53q97ls0hz8nz12fia389ygkqq9nzxn2-ruby-2.3.1-p0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /root/.nix-profile/lib/go2nix/go.rb:1:in `<top (required)>'
    from /nix/store/53q97ls0hz8nz12fia389ygkqq9nzxn2-ruby-2.3.1-p0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /nix/store/53q97ls0hz8nz12fia389ygkqq9nzxn2-ruby-2.3.1-p0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /root/.nix-profile/lib/go2nix.rb:1:in `<top (required)>'
    from /nix/store/53q97ls0hz8nz12fia389ygkqq9nzxn2-ruby-2.3.1-p0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /nix/store/53q97ls0hz8nz12fia389ygkqq9nzxn2-ruby-2.3.1-p0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /root/.nix-profile/bin/go2nix:6:in `<main>'
```

maybe https://github.com/brianmario/yajl-ruby/issues/116 helps?

## Technical details
- System: 16.09.git.a97df89 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre88185.52a875f" (nixos-unstable)
